// mem AI Worker — Processor gRPC contract.
//
// This proto is the contract between the Go backend (server/internal/workerpb)
// and the Python AI Worker (worker/mem_worker). It mirrors the Processor
// abstraction defined in SPEC.md §9.1 ProcessResult.
//
// Version: v0.1 (W1). Backwards-incompatible changes require a bump.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: processor.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessStatus int32

const (
	ProcessStatus_STATUS_UNSPECIFIED ProcessStatus = 0
	ProcessStatus_STATUS_OK          ProcessStatus = 1
	ProcessStatus_STATUS_PARTIAL     ProcessStatus = 2 // some embeddings produced, some failed
	ProcessStatus_STATUS_FAILED      ProcessStatus = 3
	ProcessStatus_STATUS_SKIPPED     ProcessStatus = 4 // no processor matched / unsupported mime
)

// Enum value maps for ProcessStatus.
var (
	ProcessStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_PARTIAL",
		3: "STATUS_FAILED",
		4: "STATUS_SKIPPED",
	}
	ProcessStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_PARTIAL":     2,
		"STATUS_FAILED":      3,
		"STATUS_SKIPPED":     4,
	}
)

func (x ProcessStatus) Enum() *ProcessStatus {
	p := new(ProcessStatus)
	*p = x
	return p
}

func (x ProcessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_processor_proto_enumTypes[0].Descriptor()
}

func (ProcessStatus) Type() protoreflect.EnumType {
	return &file_processor_proto_enumTypes[0]
}

func (x ProcessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessStatus.Descriptor instead.
func (ProcessStatus) EnumDescriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_processor_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_processor_proto_enumTypes[1]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{9, 0}
}

type ProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File identity (mirrors files.id in PostgreSQL).
	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// Where to read the bytes from. Currently only "s3://bucket/key" is supported.
	// Future: "file:///abs/path", "http(s)://...".
	StorageUri string `protobuf:"bytes,2,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	// MIME type as detected by the Go backend (magic-number based, not extension).
	Mime string `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	// Content hash (sha256, hex). For idempotency / dedup; the worker MUST NOT
	// re-fetch when the hash matches a cache hit (future optimization).
	Sha256 string `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Owning user. Required for per-user provider configuration / quotas.
	UserId string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Original file name (for hints to LLM/VLM: "this file is called X").
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// Free-form options forwarded from the request (e.g. provider overrides,
	// skip flags, tag hints). Serialized JSON to keep proto schema stable.
	OptionsJson   []byte `protobuf:"bytes,7,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ProcessRequest) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *ProcessRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ProcessRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ProcessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProcessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessRequest) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

type ProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mirrors SPEC §9.1 ProcessResult.
	Summary    string                `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"` // LLM summary, may be empty
	Caption    string                `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"` // VLM caption (image only), may be empty
	Tags       []string              `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`       // auto-generated tags
	Entities   []*Entity             `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	Embeddings map[string]*Embedding `protobuf:"bytes,5,rep,name=embeddings,proto3" json:"embeddings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // keys: "text", "visual", "face"
	// Free-form structured metadata (EXIF, codec info, …). JSON-encoded to keep
	// the wire schema stable as Processors add fields.
	MetadataJson []byte `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	// Which processor handled the file (for debugging / metrics).
	Processor string `protobuf:"bytes,7,opt,name=processor,proto3" json:"processor,omitempty"`
	// Pipeline-level status, in case partial success matters.
	Status        ProcessStatus `protobuf:"varint,8,opt,name=status,proto3,enum=mem.worker.v1.ProcessStatus" json:"status,omitempty"`
	Error         string        `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"` // non-empty if status == STATUS_FAILED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ProcessResponse) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *ProcessResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProcessResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ProcessResponse) GetEmbeddings() map[string]*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *ProcessResponse) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *ProcessResponse) GetProcessor() string {
	if x != nil {
		return x.Processor
	}
	return ""
}

func (x *ProcessResponse) GetStatus() ProcessStatus {
	if x != nil {
		return x.Status
	}
	return ProcessStatus_STATUS_UNSPECIFIED
}

func (x *ProcessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type: "person" | "place" | "org" | "event" | …  (SPEC §6.1 entities.type)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // may be empty for unnamed face clusters
	// Free-form per-entity metadata (e.g. face bbox, gps lat/lng). JSON.
	MetadataJson  []byte  `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Confidence    float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0 – 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{2}
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *Entity) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type Embedding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The provider used to generate this vector (e.g. "ollama:nomic-embed-text").
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Dimensionality (redundant with len(values[i]) but useful for early checks).
	Dim int32 `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	// One or more vectors. Single-vector kinds (visual) have len(rows) == 1;
	// multi-vector kinds (text chunks, faces) have len(rows) == N.
	Rows          []*EmbeddingRow `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{3}
}

func (x *Embedding) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Embedding) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *Embedding) GetRows() []*EmbeddingRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type EmbeddingRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The vector itself. Length must equal Embedding.dim.
	Values []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	// For text: chunk index. For face: face index. -1 if not applicable.
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// For text: the chunk text. For face: empty.
	ChunkText string `protobuf:"bytes,3,opt,name=chunk_text,json=chunkText,proto3" json:"chunk_text,omitempty"`
	// Free-form per-row metadata (e.g. face bbox). JSON.
	MetadataJson  []byte `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRow) Reset() {
	*x = EmbeddingRow{}
	mi := &file_processor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRow) ProtoMessage() {}

func (x *EmbeddingRow) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRow.ProtoReflect.Descriptor instead.
func (*EmbeddingRow) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingRow) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *EmbeddingRow) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EmbeddingRow) GetChunkText() string {
	if x != nil {
		return x.ChunkText
	}
	return ""
}

func (x *EmbeddingRow) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owning user — used for per-user provider lookup.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Ordered messages, OpenAI-style. First is typically "system", last "user".
	Messages []*ChatMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	// Optional provider override "<vendor>:<model>". Empty = user's configured llm spec.
	LlmProvider string `protobuf:"bytes,3,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"`
	// Free-form options (max_tokens, temperature, …). JSON.
	OptionsJson   []byte `protobuf:"bytes,4,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_processor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{5}
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *ChatRequest) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "system" | "user" | "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_processor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                 // assistant reply
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`                               // which provider actually answered
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                     // non-empty when status != STATUS_OK
	Status        ProcessStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=mem.worker.v1.ProcessStatus" json:"status,omitempty"` // reuse pipeline status enum
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_processor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{7}
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ChatResponse) GetStatus() ProcessStatus {
	if x != nil {
		return x.Status
	}
	return ProcessStatus_STATUS_UNSPECIFIED
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_processor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{8}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=mem.worker.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Version       string                            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_processor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_processor_proto protoreflect.FileDescriptor

const file_processor_proto_rawDesc = "" +
	"\n" +
	"\x0fprocessor.proto\x12\rmem.worker.v1\"\xc6\x01\n" +
	"\x0eProcessRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vstorage_uri\x18\x02 \x01(\tR\n" +
	"storageUri\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12!\n" +
	"\foptions_json\x18\a \x01(\fR\voptionsJson\"\xc4\x03\n" +
	"\x0fProcessResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x121\n" +
	"\bentities\x18\x04 \x03(\v2\x15.mem.worker.v1.EntityR\bentities\x12N\n" +
	"\n" +
	"embeddings\x18\x05 \x03(\v2..mem.worker.v1.ProcessResponse.EmbeddingsEntryR\n" +
	"embeddings\x12#\n" +
	"\rmetadata_json\x18\x06 \x01(\fR\fmetadataJson\x12\x1c\n" +
	"\tprocessor\x18\a \x01(\tR\tprocessor\x124\n" +
	"\x06status\x18\b \x01(\x0e2\x1c.mem.worker.v1.ProcessStatusR\x06status\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x1aW\n" +
	"\x0fEmbeddingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.mem.worker.v1.EmbeddingR\x05value:\x028\x01\"u\n" +
	"\x06Entity\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"j\n" +
	"\tEmbedding\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim\x12/\n" +
	"\x04rows\x18\x03 \x03(\v2\x1b.mem.worker.v1.EmbeddingRowR\x04rows\"\x80\x01\n" +
	"\fEmbeddingRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x1d\n" +
	"\n" +
	"chunk_text\x18\x03 \x01(\tR\tchunkText\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\fR\fmetadataJson\"\xa4\x01\n" +
	"\vChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\bmessages\x18\x02 \x03(\v2\x1a.mem.worker.v1.ChatMessageR\bmessages\x12!\n" +
	"\fllm_provider\x18\x03 \x01(\tR\vllmProvider\x12!\n" +
	"\foptions_json\x18\x04 \x01(\fR\voptionsJson\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x90\x01\n" +
	"\fChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.mem.worker.v1.ProcessStatusR\x06status\"\x14\n" +
	"\x12HealthCheckRequest\"\xb5\x01\n" +
	"\x13HealthCheckResponse\x12H\n" +
	"\x06status\x18\x01 \x01(\x0e20.mem.worker.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02*q\n" +
	"\rProcessStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x12\n" +
	"\x0eSTATUS_PARTIAL\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03\x12\x12\n" +
	"\x0eSTATUS_SKIPPED\x10\x042\xf9\x01\n" +
	"\x10ProcessorService\x12J\n" +
	"\aProcess\x12\x1d.mem.worker.v1.ProcessRequest\x1a\x1e.mem.worker.v1.ProcessResponse\"\x00\x12A\n" +
	"\x04Chat\x12\x1a.mem.worker.v1.ChatRequest\x1a\x1b.mem.worker.v1.ChatResponse\"\x00\x12V\n" +
	"\vHealthCheck\x12!.mem.worker.v1.HealthCheckRequest\x1a\".mem.worker.v1.HealthCheckResponse\"\x00B>Z<github.com/PeterGuy326/mem/server/internal/workerpb;workerpbb\x06proto3"

var (
	file_processor_proto_rawDescOnce sync.Once
	file_processor_proto_rawDescData []byte
)

func file_processor_proto_rawDescGZIP() []byte {
	file_processor_proto_rawDescOnce.Do(func() {
		file_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_processor_proto_rawDesc), len(file_processor_proto_rawDesc)))
	})
	return file_processor_proto_rawDescData
}

var file_processor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_processor_proto_goTypes = []any{
	(ProcessStatus)(0),                     // 0: mem.worker.v1.ProcessStatus
	(HealthCheckResponse_ServingStatus)(0), // 1: mem.worker.v1.HealthCheckResponse.ServingStatus
	(*ProcessRequest)(nil),                 // 2: mem.worker.v1.ProcessRequest
	(*ProcessResponse)(nil),                // 3: mem.worker.v1.ProcessResponse
	(*Entity)(nil),                         // 4: mem.worker.v1.Entity
	(*Embedding)(nil),                      // 5: mem.worker.v1.Embedding
	(*EmbeddingRow)(nil),                   // 6: mem.worker.v1.EmbeddingRow
	(*ChatRequest)(nil),                    // 7: mem.worker.v1.ChatRequest
	(*ChatMessage)(nil),                    // 8: mem.worker.v1.ChatMessage
	(*ChatResponse)(nil),                   // 9: mem.worker.v1.ChatResponse
	(*HealthCheckRequest)(nil),             // 10: mem.worker.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 11: mem.worker.v1.HealthCheckResponse
	nil,                                    // 12: mem.worker.v1.ProcessResponse.EmbeddingsEntry
}
var file_processor_proto_depIdxs = []int32{
	4,  // 0: mem.worker.v1.ProcessResponse.entities:type_name -> mem.worker.v1.Entity
	12, // 1: mem.worker.v1.ProcessResponse.embeddings:type_name -> mem.worker.v1.ProcessResponse.EmbeddingsEntry
	0,  // 2: mem.worker.v1.ProcessResponse.status:type_name -> mem.worker.v1.ProcessStatus
	6,  // 3: mem.worker.v1.Embedding.rows:type_name -> mem.worker.v1.EmbeddingRow
	8,  // 4: mem.worker.v1.ChatRequest.messages:type_name -> mem.worker.v1.ChatMessage
	0,  // 5: mem.worker.v1.ChatResponse.status:type_name -> mem.worker.v1.ProcessStatus
	1,  // 6: mem.worker.v1.HealthCheckResponse.status:type_name -> mem.worker.v1.HealthCheckResponse.ServingStatus
	5,  // 7: mem.worker.v1.ProcessResponse.EmbeddingsEntry.value:type_name -> mem.worker.v1.Embedding
	2,  // 8: mem.worker.v1.ProcessorService.Process:input_type -> mem.worker.v1.ProcessRequest
	7,  // 9: mem.worker.v1.ProcessorService.Chat:input_type -> mem.worker.v1.ChatRequest
	10, // 10: mem.worker.v1.ProcessorService.HealthCheck:input_type -> mem.worker.v1.HealthCheckRequest
	3,  // 11: mem.worker.v1.ProcessorService.Process:output_type -> mem.worker.v1.ProcessResponse
	9,  // 12: mem.worker.v1.ProcessorService.Chat:output_type -> mem.worker.v1.ChatResponse
	11, // 13: mem.worker.v1.ProcessorService.HealthCheck:output_type -> mem.worker.v1.HealthCheckResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_processor_proto_init() }
func file_processor_proto_init() {
	if File_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_processor_proto_rawDesc), len(file_processor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_processor_proto_goTypes,
		DependencyIndexes: file_processor_proto_depIdxs,
		EnumInfos:         file_processor_proto_enumTypes,
		MessageInfos:      file_processor_proto_msgTypes,
	}.Build()
	File_processor_proto = out.File
	file_processor_proto_goTypes = nil
	file_processor_proto_depIdxs = nil
}
