import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';

// The snapshot, not this compatibility adapter, owns palette values.
const revision = '910456901dda74da4d5b0320cd03d36ad18650b0';
const root = new URL('../', import.meta.url);
const source = await readFile(new URL('design-system/tokens.json', root), 'utf8');
const tokens = JSON.parse(source).tokens;
const digest = createHash('sha256').update(source).digest('hex');
assert.equal(
  digest,
  '75e62b372f23083c2f35400ce434d40bf1be098375cea85b97352dcfedbf5766',
  'Pinned upstream snapshot changed: review a new revision and its hash',
);
const value = (group, name, mode) => {
  const v = tokens[group][name].$value;
  return typeof v === 'string' ? v : v[mode];
};
const color = (name, mode) => {
  const s = value('color', name, mode);
  if (s.startsWith('#'))
    return [
      ...s
        .slice(1)
        .match(/../g)
        .map((v) => parseInt(v, 16)),
      1,
    ];
  const c = s.match(/[\d.]+/g).map(Number);
  return c.length === 3 ? [...c, 1] : c;
};
const mix = (a, b, weight) =>
  a
    .slice(0, 3)
    .map((n, i) => Math.round(n * weight + b[i] * (1 - weight)))
    .concat(1);
const luminance = (c) =>
  c
    .slice(0, 3)
    .map((v) => v / 255)
    .map((v) => (v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4))
    .reduce((sum, v, i) => sum + v * [0.2126, 0.7152, 0.0722][i], 0);
const contrast = (fg, bg) => {
  const a = luminance(mix(fg, bg, fg[3] ?? 1)),
    b = luminance(bg);
  return (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05);
};
let css = `/* GENERATED by scripts/design-tokens.mjs; DO NOT EDIT.\n * Source: bytefolk/design-system@${revision}/tokens/design-tokens.json\n * SHA-256: ${digest}; Apache-2.0 (web/design-system/LICENSE).\n */\n`;
const checks = [];
for (const mode of ['dark', 'light']) {
  const surfaces = ['canvas', 'navigation', 'surface', 'surface-inset', 'surface-raised'].map((n) =>
    color(n, mode),
  );
  const target = mode === 'dark' ? [255, 255, 255] : [0, 0, 0];
  // Preserve the upstream hue while making actual small text readable on every
  // surface. Upstream base hues are sometimes intended only for borders/icons.
  const readable = (base, tinted = false) => {
    for (let step = 0; step <= 100; step++) {
      const c =
        base[3] < 1
          ? [...base.slice(0, 3), base[3] + ((1 - base[3]) * step) / 100]
          : mix(base, target, 1 - step / 100);
      if (
        surfaces.every(
          (bg) => contrast(c, bg) >= 4.5 && (!tinted || contrast(c, mix(c, bg, 0.3)) >= 4.5),
        )
      )
        return c;
    }
    throw new Error('No readable foreground found');
  };
  const vars = {
    bg: color('canvas', mode),
    'bg-subtle': color('navigation', mode),
    'bg-panel': color('surface', mode),
    'bg-inset': color('surface-inset', mode),
    fg: color('foreground', mode),
    'fg-muted': readable(color('foreground-muted', mode)),
    'fg-subtle': readable(color('foreground-muted', mode)),
    border: color('border', mode),
    'border-strong': color('border-strong', mode),
    accent: readable(color('primary', mode), true),
    'accent-hover': readable(color('primary-hover', mode), true),
    'accent-muted': color('primary-soft', mode),
    'accent-solid': mix(color('primary', mode), [0, 0, 0], 0.8),
    'accent-solid-hover': mix(color('primary-hover', mode), [0, 0, 0], 0.7),
    'accent-foreground': color('primary-foreground', mode),
    ai: readable(color('ai', mode), true),
    success: readable(color('success-strong', mode), true),
    warn: readable(color('warning-strong', mode), true),
    danger: readable(color('danger-strong', mode), true),
  };
  for (const name of [
    'fg',
    'fg-muted',
    'fg-subtle',
    'accent',
    'accent-hover',
    'ai',
    'success',
    'warn',
    'danger',
  ]) {
    for (const bg of surfaces) {
      const ratio = contrast(vars[name], bg);
      assert.ok(ratio >= 4.5, `${mode} ${name}: ${ratio}`);
      checks.push(ratio);
    }
  }
  // Badges, selected navigation and danger-button hover compose tinted surfaces.
  for (const name of ['accent', 'accent-hover', 'ai', 'success', 'warn', 'danger']) {
    for (const bg of surfaces)
      for (const alpha of [0.05, 0.1, 0.2, 0.3]) {
        const ratio = contrast(vars[name], mix(vars[name], bg, alpha));
        assert.ok(ratio >= 4.5, `${mode} ${name} tint ${alpha}: ${ratio}`);
        checks.push(ratio);
      }
  }
  for (const name of ['accent-solid', 'accent-solid-hover']) {
    const ratio = contrast(vars['accent-foreground'], vars[name]);
    assert.ok(ratio >= 4.5, `${mode} ${name}: ${ratio}`);
    checks.push(ratio);
  }
  css += `${mode === 'dark' ? ':root, .dark' : '.light'} {\n`;
  for (const [name, c] of Object.entries(vars))
    css += `  --${name}: ${c.slice(0, 3).join(' ')};\n  --${name}-opacity: ${c[3]};\n`;
  css += `  --shadow-soft: ${value('boxShadow', 'shadow-sm', mode)};\n  --font-sans: ${value('fontFamily', 'font-sans', mode)};\n  --font-mono: ${value('fontFamily', 'font-mono', mode)};\n  color-scheme: ${mode};\n}\n`;
}
const output = new URL('src/styles/design-tokens.generated.css', root);
if (process.argv.includes('--check'))
  assert.equal(await readFile(output, 'utf8'), css, 'Regenerate shared design tokens');
else await writeFile(output, css);
console.log(
  `Shared token bridge: ${checks.length} contrast pairs >= ${Math.min(...checks).toFixed(2)}:1; ${process.argv.includes('--check') ? 'current' : 'generated'}`,
);
