apiVersion: v1
kind: Service
metadata:
  name: {{ include "mem.fullname" . }}-memd
  labels:
    {{- include "mem.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mem.componentLabels" (dict "root" . "component" "memd") | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
---
{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mem.fullname" . }}-worker
  labels:
    {{- include "mem.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mem.componentLabels" (dict "root" . "component" "worker") | nindent 4 }}
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mem.fullname" . }}-web
  labels:
    {{- include "mem.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mem.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
